name:
  .trash: 
  .git: 
  .github: 
  .DS_STORE: 
  rollup.config.js: 
  LICENSE: 
  Developer: 󰣪
  node_modules: 
  commitlint.config.ts: 󰜛
  .commitlintrc.json: 󰜛
  docker-compose.yml: 
  package.json: 
  nest-cli.json: 
  Makefile: 
  .bashrc: 
  .tmux.conf: 
  .stylua: 
  .stylua.toml: 
  .zshrc: 
  go.mod: 
  go.sum: 
  yarn-error.log: 
  yarn.lock: 
  .yarnrc: 
  pnpm-lock.yaml: 
  package-lock.json: 
  .gitignore: 
  .gitconfig: 
  .gitattributes: 
  Dockerfile: 
  .nvmrc: 
  .eslintrc.js: 
  .travis.yml: 
  .babelrc: 
  babel.config.js: 
  vite.config.js: 󰉁
  vite.config.ts: 󰉁
  Procfile: 
  .editorconfig: 
  .dockerignore: 
  .prettierignore: 󰬗
  .prettierrc: 󰬗
  .prettierrc.json: 󰬗
  .prettierrc.js: 󰬗
  prettier.config.js: 󰬗
  .prettier.yaml: 󰬗
  .env.production: 
  .env.development: 
  .env.testing: 
  .env.example: 
  .env: 
  public: 󱞊
  src: 󰲂
  fish_plugins: 󰈺
  fish_variables: 󰈺
extension:
  fish: 󰻳
  md: 
  mdx: 
  ts: 
  json: 
  log: 󰺮
  html: 
  css: 
  scss: 
  sass: 
  js: 󰌞
  mjs: 󰌞
  cjs: 󰌞
  kt: 󱈙
  png: 
  webp: 
  jpg: 
  jpeg: 
  svg: 
  mp3: 󰎆
  flac: 󰎆
  mp4: 
  out: 󱥫
  rb: 
  vue: 󰡄
  py: 
  toml: 
  lock: 
  zip: 
  xz: 
  deb: 
  rpm: 
  lua: 
  txt: 󰈙
  graphql: 
  env: 
  tf: 
  prisma: 
  pdf: 
  csv: 
  ejs: 
  jsx: 
  tsx: 
  rs: 
  xml: 
  yml: 
  yaml: 
  snap: 
  astro: 
  feature: 
  go: 
  zsh: 
  sh: 
  bash: 
  pug: 
  cpp: 
  c: 
  svelte: 
  sql: 
filetype:
  dir: 
  file: 󰈙
  executable: 󱪗
  symlink-dir: 󰉒
  symlink-file: 󰉒
